name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name fast-food-eks-cluster --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f app-secret.yml
          kubectl apply -f config-map.yml
          kubectl apply -f hpa.yml
          kubectl apply -f metrics.yml
          kubectl apply -f app-deployment.yml
          kubectl apply -f app-service.yml